version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_ZGVzaXJlZC1kcnVtLTQzLmNsZXJrLmFjY291bnRzLmRldiQ
      - CLERK_SECRET_KEY=sk_test_NHNUous5KVFL0T6WJGcrKs3NhPeOvfLANqTgs7UnML
      - NEXT_PUBLIC_ADMIN_EMAILS=annobilfrance@gmail.com,admin2@example.com
      - DATABASE_URL=mongodb+srv://france:france@cluster0.ohrhflo.mongodb.net/hyelp?retryWrites=true&w=majority
    volumes:
      - ./app:/app/app
      - ./public:/app/public
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_USER=${POSTGRES_USER:-hyelp}
      - POSTGRES_DB=${POSTGRES_DB:-hyelp}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 